#!/usr/bin/env python3
"""Regenerate firmware/src/glyph_unicode_data.h (curated PL/DE only).

Sources: font8x8 Public Domain (Latin-1); Unifont SIL OFL 1.1 (Latin Ext).
Output: 5×7 ink + 1px gutter, MSB-left (TFT Font1 advance).
"""
from __future__ import annotations

import gzip
import os
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "firmware" / "src" / "glyph_unicode_data.h"
HEX_URL = (
    "https://unifoundry.com/pub/unifont/unifont-15.1.05/"
    "font-builds/unifont-15.1.05.hex.gz"
)
EXT_URL = (
    "https://raw.githubusercontent.com/dhepper/font8x8/master/font8x8_ext_latin.h"
)
CACHE = Path(os.environ.get("UNIFONT_HEX", "/tmp/unifont-15.1.05.hex.gz"))
EXT_LATIN = Path(
    os.environ.get("FONT8X8_EXT_LATIN", "/tmp/font8x8/font8x8_ext_latin.h")
)

# German + Polish diacritics (incl. ó/Ó).
DE_PL: list[tuple[int, str]] = [
    (0x00C4, "Ä"),
    (0x00D6, "Ö"),
    (0x00DC, "Ü"),
    (0x00DF, "ß"),
    (0x00E4, "ä"),
    (0x00F6, "ö"),
    (0x00FC, "ü"),
    (0x00D3, "Ó"),
    (0x00F3, "ó"),
    (0x0104, "Ą"),
    (0x0105, "ą"),
    (0x0106, "Ć"),
    (0x0107, "ć"),
    (0x0118, "Ę"),
    (0x0119, "ę"),
    (0x0141, "Ł"),
    (0x0142, "ł"),
    (0x0143, "Ń"),
    (0x0144, "ń"),
    (0x015A, "Ś"),
    (0x015B, "ś"),
    (0x0179, "Ź"),
    (0x017A, "ź"),
    (0x017B, "Ż"),
    (0x017C, "ż"),
]
NEEDED = {cp for cp, _ in DE_PL}


def ensure(path: Path, url: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.is_file():
        print(f"downloading {url} → {path}")
        urllib.request.urlretrieve(url, path)
    return path


def load_font8x8_latin1(path: Path) -> dict[int, list[list[int]]]:
    text = path.read_text()
    m = re.search(r"font8x8_ext_latin\[96\]\[8\]\s*=\s*\{(.*)\};", text, re.S)
    if not m:
        raise SystemExit(f"could not parse {path}")
    entries = re.findall(r"\{([^}]+)\}", m.group(1))
    glyphs: dict[int, list[list[int]]] = {}
    for i in range(96):
        vals = [int(p.strip(), 0) for p in entries[i].split(",") if p.strip()]
        rows = [[(b >> x) & 1 for x in range(8)] for b in vals]
        glyphs[0xA0 + i] = rows
    return glyphs


def load_unifont_needed(path: Path) -> dict[int, list[list[int]]]:
    glyphs: dict[int, list[list[int]]] = {}
    opener = gzip.open if str(path).endswith(".gz") else open
    with opener(path, "rt") as f:
        for line in f:
            line = line.strip()
            if not line or ":" not in line:
                continue
            cp_s, hx = line.split(":", 1)
            cp = int(cp_s, 16)
            if cp not in NEEDED:
                continue
            raw = bytes.fromhex(hx)
            rows: list[list[int]] = []
            if len(raw) == 16:
                for b in raw:
                    rows.append([(b >> (7 - x)) & 1 for x in range(8)])
            elif len(raw) == 32:
                for i in range(0, 32, 2):
                    b = raw[i]
                    rows.append([(b >> (7 - x)) & 1 for x in range(8)])
            else:
                continue
            glyphs[cp] = rows
    return glyphs


def pack_font8x8(rows: list[list[int]]) -> list[int]:
    out = [0] * 8
    for y in range(7):
        bits = 0
        for x in range(5):
            if rows[y][x + 1]:
                bits |= 1 << (5 - x)
        out[y] = bits
    return out


def pack_unifont(rows: list[list[int]]) -> list[int]:
    h = len(rows)
    w = 8
    ys = [y for y in range(h) if any(rows[y])]
    xs = [x for x in range(w) if any(rows[y][x] for y in range(h))]
    if not ys or not xs:
        return [0] * 8
    y0, y1 = ys[0], ys[-1]
    x0, x1 = xs[0], xs[-1]
    out = [0] * 8
    for dy in range(7):
        sy0 = y0 + dy * (y1 - y0 + 1) // 7
        sy1 = y0 + (dy + 1) * (y1 - y0 + 1) // 7
        sy1 = max(sy1, sy0 + 1)
        bits = 0
        for dx in range(5):
            sx0 = x0 + dx * (x1 - x0 + 1) // 5
            sx1 = x0 + (dx + 1) * (x1 - x0 + 1) // 5
            sx1 = max(sx1, sx0 + 1)
            on = False
            for sy in range(sy0, min(sy1, h)):
                for sx in range(sx0, min(sx1, w)):
                    if rows[sy][sx]:
                        on = True
                        break
                if on:
                    break
            if on:
                bits |= 1 << (5 - dx)
        out[dy] = bits
    return out


def main() -> None:
    ensure(CACHE, HEX_URL)
    ensure(EXT_LATIN, EXT_URL)
    f8 = load_font8x8_latin1(EXT_LATIN)
    uni = load_unifont_needed(CACHE)

    glyphs: dict[int, list[int]] = {}
    for cp, _name in DE_PL:
        if cp <= 0xFF and cp in f8:
            glyphs[cp] = pack_font8x8(f8[cp])
        else:
            glyphs[cp] = pack_unifont(uni[cp])

    lines = [
        "// Auto-generated by firmware/scripts/gen_unicode_glyphs.py — do not edit.",
        "// Curated PL/DE only: 5×7 ink + 1px gutter, MSB-left.",
        "// Latin-1: font8x8 (Public Domain). Latin Ext: Unifont 15.1.05 (SIL OFL 1.1).",
        "#pragma once",
        "#include <stdint.h>",
        "#if defined(ARDUINO) || defined(ESP_PLATFORM)",
        "#include <pgmspace.h>",
        "#else",
        "#ifndef PROGMEM",
        "#define PROGMEM",
        "#endif",
        "#ifndef pgm_read_byte",
        "#define pgm_read_byte(addr) (*(const uint8_t *)(addr))",
        "#endif",
        "#ifndef pgm_read_word",
        "#define pgm_read_word(addr) (*(const uint16_t *)(addr))",
        "#endif",
        "#endif",
        "",
        "struct GlyphBitmap {",
        "  uint16_t cp;",
        "  uint8_t rows[8];",
        "};",
        "",
        f"static const GlyphBitmap kGlyphPlDe[{len(DE_PL)}] PROGMEM = {{",
    ]
    for cp, name in DE_PL:
        g = glyphs[cp]
        hexes = ", ".join(f"0x{b:02X}" for b in g)
        lines.append(f"  {{0x{cp:04X}, {{{hexes}}}}}, // {name}")
    lines += [
        "};",
        "",
        f"static constexpr unsigned kGlyphPlDeCount = {len(DE_PL)};",
        "",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(DE_PL)} glyphs)")


if __name__ == "__main__":
    main()
